branches = ["master"]

[plugins]
"@semantic-release/gitlab" = {}
"@semantic-release/github" = {}
"@semantic-release/changelog" = {}
"@semantic-release/commit-analyzer" = { preset = "conventional" }
"@semantic-release/release-notes-generator" = {}
"@semantic-release/git" = {}

[[plugins]]
path = "@semantic-release/git"
assets = ["meteocatpy/version.py"]
message = "chore(release): update version to ${nextRelease.version}"
